import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Welcome from "@/components/Welcome";
import User from "@/components/User";
import Description from "@/components/Description";
import Pet from "@/components/Pet";
import Counter from "@/components/Counter";
import UserForm from "@/components/UserForm";

export default function Home() { // Componentes - funções 
  return (
    // Fragment - Envolve as tags que contem o conteúdo do site(elemento pai)
    <>
      <Head>
        <title>Fundamento do React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello World! Meu primeiro site em React!</h1>
        <Welcome />
        <User />
        {/* Passando o props para o componentes */}
        <Description city="Registro" age={21} email="catarine@email.com" />
        {/* Componente com desestruração de props */}
        <Pet name="Cake" breed="Vira-lata" age={6}/>
        {/* Importando o Contador (utilizando estados) */}
        <br />
        <Counter />
        <br />
        <UserForm />
      </main>
    </>
  );
}
